name: Update Deno Dependencies

on:
  schedule:
    # Run every Saturday at 10:00 JST.
    - cron: "0 1 * * 6"

  # For debug
  workflow_dispatch:

jobs:
  udd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - name: Update Dependencies
        run: make update-deps > ../output.txt
        env:
          NO_COLOR: 1
      - name: Read ../output.txt
        id: read-output
        uses: juliangruber/read-file-action@v1
        with:
          path: ../output.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: |
            Update Deno dependencies

            ```sh
            $ make update-deps
            ```

            ```
            ${{ steps.read-output.outputs.content }}
            ```
          title: Update Deno Dependencies
          body: |
            ```sh
            $ make update-deps
            ```

            ```
            ${{ steps.read-output.outputs.content }}
            ```
          branch: update-deno-dependencies
          delete-branch: true
          assignees: kg8m
